Added Table for Meals, incl. fixtures, tests, and stories
ucsb-cs156-f24/proj-dining-f24-15 pull request #40
Opened 2024-11-20 07:53 UTC by haohuant

closes: #16 

This frontend change adds a table so that users can see what meals are served at a dining hall on a particular day (ex. breakfast, lunch, dinner). 
- [ ] the table exists in storybook with appropriate values

![Screenshot 2024-11-19 233011](https://github.com/user-attachments/assets/78aa17d5-fc3c-40cd-a1fc-35f0f78fa8a8)
![Screenshot 2024-11-19 233030](https://github.com/user-attachments/assets/5607e4d0-4a9f-47ef-989b-c5c712deb24a)

Storybook link: https://6736bc30cc8f2118f61238ed-dbrfhqxlio.chromatic.com/?path=/docs/components-meals-mealstable--docs

2024-11-24 17:10 UTC, sophiaray2101 approved these changes, later dismissed
LGTM, everything is viewed correctly on storybook

2024-11-25 00:27 UTC, pconrad requested changes
There are some stryker exceptions that don't seem to be doing anything.

2024-11-25 00:27 UTC, pconrad commented on frontend/src/main/components/Meals/MealsTable.js
> +  // Stryker restore all
We can probably remove both of these since they are not doing anything?

2024-11-25 00:27 UTC, pconrad commented on frontend/src/main/components/Meals/MealsTable.js
> +  // Stryker disable next-line all : TODO try to make a good test for this
And this too?

2024-11-25 00:27 UTC, pconrad commented on frontend/src/main/components/Meals/MealsTable.js
> +  // Stryker restore all
```suggestion

```

2024-11-25 00:27 UTC, pconrad commented on frontend/src/main/components/Meals/MealsTable.js
> +  // Stryker disable next-line all : TODO try to make a good test for this
```suggestion

```

2024-11-25 00:27 UTC, pconrad commented on frontend/src/main/components/Meals/MealsTable.js
> +  // Stryker disable all : hard to test for query caching
```suggestion

```

2024-11-25 00:29 UTC, pconrad submitted a review, later dismissed
LGTM

2024-11-25 07:57 UTC, pconrad approved these changes
LGTM

2024-11-25 07:57 UTC, merged