MenuItemReview post (all users) and get all (admin only)
ucsb-cs156-f24/proj-dining-f24-15 pull request #50
Opened 2024-11-24 18:49 UTC by sophiaray2101

dokku link: https://proj-dining-sophiaray2101.dokku-15.cs.ucsb.edu/

- [ ] Created the controller and test files for the get all and post
- [ ] 100% jacoco test coverage
- [ ] 100% mutation coverage
- [ ] works on both localhost and dokku

What to test:
1. Make sure on dokku you can get all if you are an admin user, but that you are forbidden trying to get all as a regular user
2. Make sure that if you are not logged in you cannot get all or post

As of right now, the MenuItem controls are not implement. This means that since the POST for this requires checking if a menuItem ID exists or not, any time you try to post into the menuItemReview, it will give a 404 error of "not found", meaning the linked menuItem ID was not found, thus you cannot attach a review to a non existent menu item. I will work on this next. The post should still work, but I will try to get the menuItem controller for post down as fast as I can (maybe before this PR gets reviewed).

<img width="713" alt="Screenshot 2024-11-24 at 10 47 27 AM" src="https://github.com/user-attachments/assets/3c57e0ef-6470-4357-a906-0568355a5ae5">

2024-11-24 19:36 UTC, riasinha commented
LGTM - tested get all on dokku for admin user and forbidden user and works as expected

2024-11-24 19:40 UTC, riasinha approved these changes, later dismissed
LGTM - tested on dokku as admin and restricted user

2024-11-25 08:08 UTC, pconrad requested changes
Some crucial changes that need to be made here.

2024-11-25 08:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
> +            @Parameter(name="studentUserId") @RequestParam long studentUserId,
```suggestion

```

Instead, assign `studentUserId = currentUser.getId();` inside the controller

2024-11-25 08:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
> +            @Parameter(name="status") @RequestParam String status,
```suggestion
          
```
Instead, assign status = "Awaiting Moderation"

2024-11-25 08:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
> +            @Parameter(name="moderatorUserId") @RequestParam long moderatorUserId,
```suggestion

```

We don't know who the moderator will be.  That is determined when a moderator brings up the list of reviews awaiting moderation and clicks on one.  

Instead, assign 1moderatorId = null;` inside the controller

2024-11-25 08:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
> +            @Parameter(name="moderatorComments") @RequestParam String moderatorComments,
```suggestion

```

How could the user possibly know what the moderators comments are going to be?  Assign to null inside the controller.

2024-11-25 08:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
> +            @Parameter(name="createdDate", description="date (in iso format, e.g. YYYY-mm-ddTHH:MM:SS") @RequestParam("createdDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime
This should be set to the current date and time (`now`) inside the controller, or better yet, assigned using the techniques described here:

https://ucsb-cs156.github.io/topics/spring_boot/spring_boot_database.html#timestamps-on-database-rows

2024-11-25 08:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
> +            @Parameter(name="lastEditedDate", description="date (in iso format, e.g. YYYY-mm-ddTHH:MM:SS") @RequestParam("lastEditedDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDat
You forgot the two most important things!!!! 

The whole point of creating a review is to give the item a number of stars (1-5) and write some text about how much you loved or hated the food!

Where are those two parameters?

2024-11-25 08:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
> +            @Parameter(name="lastEditedDate", description="date (in iso format, e.g. YYYY-mm-ddTHH:MM:SS") @RequestParam("lastEditedDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDat
```suggestion
           
```

Last edited date should be set either automatically using the techniques here:

https://ucsb-cs156.github.io/topics/spring_boot/spring_boot_database.html#timestamps-on-database-rows

Or it should be set inside the controller in the POST and PUT methods, plus any method that the moderator uses to change the status.

Allowing the *user* to input this means they can choose any date/time they want, in the past, present or future.  What would be the purpose of the field if the user can make it say anything they want?

It's so important to keep the use case and the user story in mind when writing code for real applications!

2024-11-25 08:08 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/dining/controllers/MenuItemReviewController.java
> +    }
What's the use case for this?

I do understand why an admin would need to list all reviews that have the status "Awaiting Moderation". But when would they just need to see a list of all the reviews?

2024-11-26 04:11 UTC, pconrad approved these changes, later dismissed
LGTM... will test on dokku

2024-11-26 22:51 UTC, pconrad approved these changes
LGTM... will test on dokku

2024-11-26 22:55 UTC, merged